import type { ThemeDefinition } from "vuetify/lib/framework.mjs";

export const aquaSplashTheme: ThemeDefinition ={
    dark: true,
    colors: {
      primary: "#B2C5FF",
      "onPrimary": "#002C72",
      "primaryContainer": "#104199",
      "onPrimaryContainer": "#DAE2FF",
      "primaryFixed": "#DAE2FF",
      "onPrimaryFixed": "#001847",
      "primaryFixedDim": "#B2C5FF",
      "onPrimaryFixedVariant": "#104199",
      secondary: "#C0C6DD",
      "onSecondary": "#2A3042",
      "secondaryContainer": "#404659",
      "onSecondaryContainer": "#DCE2F9",
      "secondaryFixed": "#DCE2F9",
      "onSecondaryFixed": "#151B2C",
      "secondaryFixedDim": "#C0C6DD",
      "onSecondaryFixedVariant": "#404659",
      "tertiary": "#E1BBDD",
      "onTertiary": "#412742",
      "tertiaryContainer": "#5A3D59",
      "onTertiaryContainer": "#FED7F9",
      "tertiaryFixed": "#FED7F9",
      "onTertiaryFixed": "#2B122C",
      "tertiaryFixedDim": "#E1BBDD",
      "onTertiaryFixedVariant": "#5A3D59",
      "error": "#FFB4AB",
      "onError": "#690005",
      "errorContainer": "#93000A",
      "onErrorContainer": "#FFDAD6",
      "outline": "#8F9099",
      "background": "#1B1B1F",
      "onBackground": "#E4E2E6",
      "surface": "#131316",
      "onSurface": "#C7C6CA",
      "surfaceVariant": "#45464F",
      "onSurfaceVariant": "#C5C6D0",
      "inverseSurface": "#E4E2E6",
      "inverseOnSurface": "#1B1B1F",
      "inversePrimary": "#325AB2",
      "shadow": "#000000",
      "surfaceTint": "#B2C5FF",
      "outlineVariant": "#45464F",
      "scrim": "#000000",
      "surfaceContainerHighest": "#343438",
      "surfaceContainerHigh": "#292A2D",
      "surfaceContainer": "#1F1F23",
      "surfaceContainerLow": "#1B1B1F",
      "surfaceContainerLowest": "#0D0E11",
      "surfaceBright": "#39393C",
      "surfaceDim": "#131316"
    },
}