import type { ThemeDefinition } from "vuetify/lib/framework.mjs";

export const aquaSplashTheme: ThemeDefinition ={
    dark: true,
    colors: {
      primary: "#B2C5FF",
      "on-primary": "#002C72",
      "primary-container": "#104199",
      "on-primaryContainer": "#DAE2FF",
      "primary-fixed": "#DAE2FF",
      "on-primary-fixed": "#001847",
      "primary-fixed-dim": "#B2C5FF",
      "on-primary-fixed-variant": "#104199",
      secondary: "#C0C6DD",
      "on-secondary": "#2A3042",
      "secondary-container": "#404659",
      "on-secondary-container": "#DCE2F9",
      "secondary-fixed": "#DCE2F9",
      "on-secondary-fixed": "#151B2C",
      "secondary-fixed-dim": "#C0C6DD",
      "on-secondary-fixed-variant": "#404659",
      "tertiary": "#E1BBDD",
      "on-tertiary": "#412742",
      "tertiary-container": "#5A3D59",
      "on-tertiary-container": "#FED7F9",
      "tertiary-fixed": "#FED7F9",
      "on-tertiary-fixed": "#2B122C",
      "tertiary-fixed-dim": "#E1BBDD",
      "on-tertiary-fixed-variant": "#5A3D59",
      "error": "#FFB4AB",
      "on-error": "#690005",
      "error-container": "#93000A",
      "on-error-container": "#FFDAD6",
      "outline": "#8F9099",
      "background": "#1B1B1F",
      "on-background": "#E4E2E6",
      "surface": "#131316",
      "on-surface": "#C7C6CA",
      "surface-variant": "#45464F",
      "on-surface-variant": "#C5C6D0",
      "inverse-surface": "#E4E2E6",
      "inverse-on-surface": "#1B1B1F",
      "inverse-primary": "#325AB2",
      "shadow": "#000000",
      "surface-tint": "#B2C5FF",
      "outline-variant": "#45464F",
      "scrim": "#000000",
      "surface-container-highest": "#343438",
      "surface-container-high": "#292A2D",
      "surface-container": "#1F1F23",
      "surface-container-low": "#1B1B1F",
      "surface-container-lowest": "#0D0E11",
      "surface-bright": "#39393C",
      "surface-dim": "#131316"
    },
}