import type { ThemeDefinition } from "vuetify/lib/framework.mjs";

export const darkTheme: ThemeDefinition ={
    dark: true,
    colors: {
      primary: "#FFBA32",
      "on-primary": "#422C00",
      "primary-container": "#5F4100",
      "on-primary-container": "#FFDEAB",
      "primary-fixed": "#FFDEAB",
      "on-primary-fixed": "#271900",
      "primary-fixed-dim": "#FFBA32",
      "on-primary-fixed-variant": "#5F4100",
      secondary: "#DBC3A1",
      "on-secondary": "#3C2E16",
      "secondary-container": "#54442A",
      "on-secondary-container": "#F8DFBB",
      "secondary-fixed": "#F8DFBB",
      "on-secondary-fixed": "#261904",
      "secondary-fixed-dim": "#DBC3A1",
      "on-secondary-fixed-variant": "#54442A",
      "tertiary": "#B4CEA5",
      "on-tertiary": "#213618",
      "tertiary-container": "#374D2D",
      "on-tertiary-container": "#D0EABF",
      "tertiary-fixed": "#D0EABF",
      "on-tertiary-fixed": "#0C2006",
      "tertiary-fixed-dim": "#B4CEA5",
      "on-tertiary-fixed-variant": "#374D2D",
      "error": "#FFB4AB",
      "on-error": "#690005",
      "error-container": "#93000A",
      "on-error-container": "#FFDAD6",
      "outline": "#9B8F80",
      background: "#1F1B16",
      "on-background": "#EAE1D9",
      
      surface: "#16130E",
      "on-surface": "#CDC5BD",
      "surface-variant": "#4E4539",
      "on-surface-variant": "#D2C5B4",
      "inverse-surface": "#EAE1D9",
      "inverse-on-surface": "#1F1B16",
      "inverse-primary": "#7E5700",
      "shadow": "#000000",
      "surface-tint": "#FFBA32",
      "outline-variant": "#4E4539",
      "scrim": "#000000",
      "surface-container-highest": "#38342E",
      "surface-container-high": "#2D2924",
      "surface-container": "#231F1A",
      "surface-container-low": "#1F1B16",
      "surface-container-lowest": "#110E09",
      "surface-bright": "#3D3833",
      "surface-dim": "#16130E"
    },
}